### ISSUE TITLE
banana 1.5 - default Time Field setting?

### ISSUE THREAD

**Issue by dougmcclure** [lucidworks/banana#106]
Where can I set the default Time Field setting so each new dashboard has it properly set?

**Comment by aadel** [comment]
Doug,

You just need to update time field properties inside `dashboard-nts.json` and `dashboard-ts.json` files under `src/app/dashboards` directory.

**Comment by dougmcclure** [comment]
Yep, I've set that and still have to manually change it for a new
dashboard. It keeps showing event_timestamp.

boards]$ cat default-ts.json | grep time
          "type": "time",
          "type": "timepicker",
          "time_options": [
          "timespan": "15m",
          "timefield": "timestamp",
          "timeformat": "",
          "time_field": "timestamp",
          "timezone": "browser",

**Comment by aadel** [comment]
Doug,

Please check here 55f51dcd665a1f7a32b852fddcd1d309daf12428. After applying this, timefield will be read from `src/config.js` along with other default dashboard settings.

**Comment by dougmcclure** [comment]
I manually applied those changes, cleared caches and verified that the
timestamp field is properly set for a new dashboard page.

Thanks!

**Comment by aadel** [comment]
Thanks for the verification! Closed via https://github.com/LucidWorks/banana/pull/107
