### ISSUE TITLE
banana 1.5 - filter panel - toggle on/off not updating other panels

### ISSUE THREAD

**Issue by dougmcclure** [lucidworks/banana#110]
When I toggle a filter on/off I'm expecting all other panels to update accordingly. It's only when I delete the filter that the other panels are updated. Using FF 31.4 or Chrome 40 (64b) give me the same results.

**Comment by tarek-salah** [comment]
Thanks for the report . We will work on it

**Comment by aadel** [comment]
Closed by https://github.com/LucidWorks/banana/pull/114
