### ISSUE TITLE
Error  Oops! undefined field: "event_timestamp"  with Banana 

### ISSUE THREAD

**Issue by ykheddar** [lucidworks/banana#119]
Hello,

Can you help me to resolve this problem.

When I execute a query on Banana I have a error :  "Oops! undefined field: "event_timestamp"  "

Thanks.

Youcef

**Comment by tarek-salah** [comment]
this is can be solved by opening the configuration for the panel and check the time field
the time field must be field in solr core
for example to set time field in time picker panel
![selection_086](https://cloud.githubusercontent.com/assets/7497722/5936739/0ed978c2-a6f0-11e4-9af2-1fc4086105d1.png)

event_timestamp is field is solr core

**Comment by ykheddar** [comment]
Thank you dear tarek-salah.

**Comment by ykheddar** [comment]
Tarek-Salah,

Can you specify the name of file that I need to modify to resolve this issue?

Thnx.

**Comment by tarek-salah** [comment]
You don't need to modify any file 
just from the configuration for any panel you can change the field
![selection_087](https://cloud.githubusercontent.com/assets/7497722/5954706/a288204c-a7a3-11e4-92b2-d011bb1a1920.png)
