### ISSUE TITLE
Pie graph got bugs in term panel.

### ISSUE THREAD

**Issue by suhyunjeon** [lucidworks/banana#123]
I used many pie graph in a dashboard. 

When they have data, they did not show the bugs.
But if they don't have data(when I searched a new condition), they shows the bugs.

[ web browser : Chrome 39.0.2171.65 (64-bit) ]
When I using a mouseover in pie chart panel, they got bugs like this.
1. Uncaught TypeError: Cannot read property 'autoHighlight' of undefined
2. Uncaught TypeError: Cannot read property 'trigger' of null

I checked and debug the source code in jquery.flot.pie.js( {$BANANA_HOME}/public/vendor/jquery/jquery.flot.pie.js). 
They dont have problem. Who knows the problem. Help me please.

**Comment by aadel** [comment]
Hi,

Please post the dashboard JSON that produces this issue so we can take deeper look. Also, which version/branch of Banana are you using?

**Comment by suhyunjeon** [comment]
It's 1.4 version. Tell me your email address. I will send an email attached json file.

**Comment by aadel** [comment]
I think it's easier to save the dashboard to a gist and post the URL.

**Comment by suhyunjeon** [comment]
I know what it is. I already used to gist uploaded. but I dont want to open
a json file. It is a job for company. So I wanted to send you a file.

2015년 2월 5일 목요일, Ahmed Adelnotifications@github.com님이 작성한 메시지:

**Comment by aadel** [comment]
You can use the email address on my GitHub profile page.

**Comment by suhyunjeon** [comment]
Thank you :)

2015년 2월 5일 목요일, Ahmed Adelnotifications@github.com님이 작성한 메시지:

**Comment by suhyunjeon** [comment]
미세한 자바스크립트 에러가 너무 많네요. 일일이 이슈처리하긴 힘들고..
파이어폭스와 크롬에서 나는 현상이구요.
하나씩 수정해서 문제 해결하였습니다.
