### ISSUE TITLE
Table paging is not refresh in the query panel when I try to search data. 

### ISSUE THREAD

**Issue by suhyunjeon** [lucidworks/banana#133]
Hello everyone. 
Table paging is not refresh in the query panel when I try to search data. 

First of all, I searched all data to the table panel using query panel. 

```
*:*
```

Second of all, I moved paging to third page from first page. 

```
Paging : Per page 10 * Page limit 5 = 50

- first page : 0 to 10 of 50 available for paging
- second page : 10 to 20 of 50 available for paging
- third page : 20 to 30 of 50 available for paging
```

Now I stay third page (20 to 30 of 50 available for paging).

Finally I searched a data to the table in query panel again. 

```
id:"foo bar"
```

There is no data in table panel. BUT if I move the page to first page from third page, I could see the data. 

I thought, the paging is not refresh in the table panel when I search some data againg. 
They stay the page(20 to 30 of 50 available for paging) when I see the page.

They need to refresh option when user search a data in query panel again. 

 I will be modify this issue.

**Comment by athana** [comment]
Thanks for reporting @suhyunjeon  I will fix this issue.

**Comment by suhyunjeon** [comment]
I solved the bug. I did pull request now. Check it out.
