### ISSUE TITLE
Terms panel facet sort

### ISSUE THREAD

**Issue by obiwan866** [lucidworks/banana#145]
Hi all !

i'm trying to use the terms panel to get some stats fields (sum for example).
Here is my question : i would like to sort the result by date, and not by value.
more precisely i'm doing a sum on each day (with a string date field / not the original date field in solr format), and i get these sums oredering by their value not by their date.

Any  tips about that ?

thx in advance.

**Comment by aadel** [comment]
Hi, Histogram panel seems more appropriate for your situation. You may choose values mode and cumulative option from panel settings to get cumulative values ordered by date.

**Comment by obiwan866** [comment]
Hi,  i don't think so, the cumulative option does not do the job. i get my numerical value individually.
I'm using a filter like this : &fq=indicator:Inject*. There are 5 indicators, and i would like to get the sum of those five rows (another numerical field actually). My point is to get some stats facet sorting. 
Thx.

**Comment by aadel** [comment]
Could you please provide the panel query you have?

**Comment by obiwan866** [comment]
Hi, 

i achieve my goal, with a small and ugly change in the terms panel code. So i'v got the stats (sum here) sorted by date(label actually).

Here is the query : q=indicator%3AInjectIPTVEvent*&wt=json&rows=0&fq=date:[NOW/DAY-90DAY%20TO%20NOW/DAY%2B1DAY]&stats=true&stats.facet=date_split&stats.field=value_num&facet.missing=true

**Comment by obiwan866** [comment]
Hi all, 

The feature i needed has been implemented in the term panel of the develop branch (1.5).
That's great !

Regards.
