### ISSUE TITLE
Best way to add dependecy when creating custom panel

### ISSUE THREAD

**Issue by MFrancesco** [lucidworks/banana#147]
Hi all, 
recently i saw the tutorial presented by Andrew Thanalertvisuti on how to write custom panels.
Now i need to add some custom library in order to write my panel and i was wondering on what is the best and most portable way of adding and use external resources without editing the banana source code ?
The only way i currently find is to add the library and edit the require.config.js file
Greetings
Francesco

**Comment by bverheij** [comment]
Hi Francesco,

is that tutorial on writing custom panels available online? I was looking for just that (and information on writing customer panels).

Cheers
Bas

**Comment by athana** [comment]
Hi @MFrancesco @bverheij  I will write the tutorial and post it to Banana's wiki page for you. This is a pretty busy week for me, so I will probably finish it by next week. Thanks for your interests!

**Comment by dougmcclure** [comment]
+1

**Comment by MFrancesco** [comment]
Tnx @athana and keep up the good work.
Btw for @dougmcclure https://www.youtube.com/watch?v=cqV5lPM2VVE this is a great starting point. Tomorrow i can upload a gist i created containing a skeleton panel you can easily extend.

**Comment by athana** [comment]
Hi guys! I finished writing the tutorial on how to build a custom panel. You can read it here: https://github.com/LucidWorks/banana/wiki/Tutorial:-How-to-Build-a-Custom-Panel
Any feedbacks are welcome.

**Comment by jsrfntd** [comment]
Hello @athana, I'm a developer and I'm researching on banana .I watched your conference tutorial in youtube, and I think that this is very good I have a question about that integration of D3 with banana panel. Actually i'm using banana for visualising data of some servers of my company. I developer a example with D3.js  by separate and it works, but when i try to integrate this example with a banana panel it not works. In the d3 example i visualizing data using svg circles ang generate the x and y axis through the function d3.extent. The following error in the js browser console appear:  "Error: <circle> attribute cx: Expected length, "NaN" " when i do this:

var svg = d3.select(element[0]).append("svg")
                            .attr("width", width)
                            .attr("height", height)
                            .selectAll("circle")
                            .data(scope.data)
                            .enter()
                            .append("circle");

                        var x_extend = d3.extent(scope.data, function(d) {
                            return d.id;
                        });

                        var x_scale = d3.scale.linear()
                            .range([margin, width - margin])
                            .domain(x_extend);

                        var y_extent = d3.extent(scope.data, function(d) {
                            return d.value;
                        });

                        var y_scale = d3.scale.linear()
                            .range([height - margin, margin])
                            .domain(y_extent);

                        d3.selectAll("circle")
                            .attr("r", 3)
                            .attr("cx", function(d) {
                                return x_scale(d.id)
                            })
                            .attr("cy", function(d) {
                                return y_scale(d.value)
                            });

I hope you can help me . Thanks!
