### ISSUE TITLE
Estimated release date Banana v2.0.0

### ISSUE THREAD

**Issue by bverheij** [lucidworks/banana#148]
Hi there, 

is there an estimated release date for Banana v2.0 already? 

We like to know how in order to estimate possible migration timelines (and diverting possible implementation of custom panels in the current version).

Cheers
Bas

**Comment by dougmcclure** [comment]
+1   Very interested in this also - and how much of the Kibana 4 look, feel
and panels will be supported

**Comment by Tagar** [comment]
+1

**Comment by janmejay** [comment]
Hi,

Does banana work by merging-back changes from kibana and then making changes to it? Or is it a non-converging fork of Kibana which is supposed to diverge by choice?

Should users expect all changes flowing into Kibana to come here? As in:
- is it just a mater of time?
- or will features be built from scratch, incrementally, on need basis, or based on patches received?

**Comment by janmejay** [comment]
+1 for Kibana4 features being pulled.

**Comment by Tagar** [comment]
+1 for Kibana4 features being pulled.

**Comment by nickvasilyev** [comment]
Can you guys specify some specific functionality you are looking for from Kibana 4? 

Are you looking for the general mapping of searches to panels to dashboards, or just similar visualization? 

I can tell right off the bat that some visualizations will have problems because in elastic search you are able to run an aggregation on a date range (like a combination of facet.range and facet.pivot), this is how they are able to run a lot of the cool multi series plots, I am not sure if Solr can do that now. However Solr5.1 has some new faceting capability that looks promising, but I haven't had time to play with it yet.

**Comment by dougmcclure** [comment]
The same user experience - search, visualize, dashboard. Wizard driven
visualize panel configuration. Start anyplace - with a search, saved search
or saved panel.  As much of the panel type and functionality as Solr 5.x
plus any that stats/analtyic components could offer (eg Bloomberg stuff or
similar from LucidWorks, Heliosearch, etc). Stats on any/all panels where
possible. Exporting data from any panel, not just table.

**Comment by nickvasilyev** [comment]
Thanks Doug, that clears things up a bit. I am not really on the dev team, so I am not sure what they are planning. 

In the meantime, here is a sunburst panel, hope it helps:
https://github.com/LucidWorks/banana/pull/169

**Comment by athana** [comment]
Currently we are working on porting Kibana 4 to Banana 4. Due to time and resource constraints, we have to put Banana 2 (dev-2.0 branch) on hold for now. Banana 4 will have the same look and feel as Kibana 4, minus elasticsearch-specific features. We plan to release Banana 4 in May or June, and after that, we will come back to finish the Banana 2.

**Comment by athana** [comment]
@janmejay Banana 1.x and 2 are non-converging forks of Kibana. This is by choice because we have to make many changes to elasticsearch-specific codes and UIs in Kibana, in order to support Solr. Some features that can be ported to Banana will be ported, otherwise, we will have to build them from scratch. For the upcoming Banana 4, it will be a non-converging fork as well.

**Comment by fxprunayre** [comment]
@athana any public repo where we could follow what is going on (or even maybe help) on Banana 4 ?

**Comment by athana** [comment]
@fxprunayre not yet. We will open the repo at the same time we release Banana 4. Thanks for offering your help. I'm appreciated it.

**Comment by jblang** [comment]
Any update on the release date for Banana 4?

**Comment by fxprunayre** [comment]
@athana any updates on Banana 4 repo location and release date ?

**Comment by athana** [comment]
@fxprunayre @jblang @nickvasilyev @dougmcclure @bverheij @Tagar @janmejay 
Update: I'm currently working on releasing the public repo for Banana4. It will be renamed and located in a new repo called [Silk](https://github.com/LucidWorks/silk). The target date is by Aug 7, 2015.

**Comment by Tagar** [comment]
I like the new repo name. thanks!
will it be the same as the commercial Silk product?
https://lucidworks.com/fusion/silk/

**Comment by athana** [comment]
@Tagar Yes, it will be the same.

**Comment by janmejay** [comment]
Awesome!

## 

Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by athana** [comment]
@fxprunayre @jblang @nickvasilyev @dougmcclure @bverheij @Tagar @janmejay 
Update: [Silk](https://github.com/LucidWorks/silk) is ready. I'm just waiting for approval to open the public access from my company. This should only take a few days. Stay tuned guys!

**Comment by janmejay** [comment]
Wonderful! looking forward to it.

**Comment by ac7ionabl3** [comment]
Should we expect any performance enhancements? E.g. faster display on reload, or when the dashboard has numerous panels, or faster display for individual panels?

**Comment by jblang** [comment]
@athana Any update? Sorry to bug you about this but I'm working on a project and I'm trying to decide to go with Banana 1.5 or wait for Silk.

**Comment by athana** [comment]
@ac7ionabl3  There might be some performance enhancements, mostly due to the use of newer versions of JS libraries.
@jblang No problem, and sorry about the delay. Currently my team is reviewing the Silk repo and revising documentations. I think it should not take more than a week or two.

**Comment by CaryBourgeois** [comment]
Any updates on availability at this point?

**Comment by suhyunjeon** [comment]
I am waiting SiLK next version!

**Comment by jblang** [comment]
@athana Any update?

**Comment by jblang** [comment]
@athana ping

**Comment by ac7ionabl3** [comment]
Any news at all? Even a guesstimate?

**Comment by natbusa** [comment]
waiting ... any news?

**Comment by athana** [comment]
Hi guys, sorry for the delay. I just ping my management team again on this and waiting for their reply. Hopefully they are ready to release it soon! I'll keep you posted.

**Comment by jblang** [comment]
Hey, it's been another 3 weeks since your last response. Just wanted to check in and get a status update.

**Comment by rajeshbabu999** [comment]
Hi athana, Thank you for this great addition to SOLR. I installed banana and it looks, works great  can't ask for anything more i thank you and your team for all your effort. This is like open source tableau on top of hadoop.

**Comment by natbusa** [comment]
what are the plans for the silk repo? 
Or should I keep following the banana repo? 
is branch 1.4.0 a port of kibana 4?

**Comment by natbusa** [comment]
what are the plans for the silk repo? 
Or should I keep following the banana repo? 
is branch 1.4.0 the port of kibana 4?

**Comment by jdrews** [comment]
@natalinobusa Banana 2.0 is a port of Kibana 4. They haven't released 2.0 yet.

**Comment by athana** [comment]
Hi guys, the silk repo is ready! You can now access it at: https://github.com/LucidWorks/silk
Thank you for your patience. @bverheij @dougmcclure @jblang @natalinobusa @suhyunjeon @fxprunayre @janmejay @Tagar
