### ISSUE TITLE
HTTP GET vs POST to execute search

### ISSUE THREAD

**Issue by iperminov** [lucidworks/banana#155]
Hi,

I have questions concerning the HTTP method to execute search.

Currently in the "dev-2.0" branch you use POST (see https://github.com/LucidWorks/banana/blob/dev-2.0/src/vendor/solrjs/solr.js#L18500). And in the "develop" branch you use GET (see https://github.com/LucidWorks/banana/blob/develop/src/vendor/solrjs/solr.js#L18501).

The request method was changed from POST to GET in the commit 43b930a6bf ("Convert post request to get request in solr client"). And there was the comment "Something does not work right with GET method" in solr.js near that change (currently in the "develop" branch this comment is removed).

I use Banana 1.5. It executes search using GET, as in the "develop" branch. In my use case I have to execute search with extremely long query string (more than 10K characters). Solr returns HTTP error 400 (bad request) because of the long query string in URL.

When I changed "get" back to "post" in doSearch(...) in solr.js, everything became fine. I use Solr Cloud 4.4.0-cdh5.2.0 and a dashboard with Timepicker, Query, Hits, Filtering, Histogram, Terms, Facet and Table panels.

My questions are: 
1. What the issue was with search using POST, which forced you to change the request method to GET?
2. Wouldn't it be better to revert the request method to POST when doing search to allow long search conditions?

Regards,
Igor

**Comment by aadel** [comment]
Solr accepts both GET and POST for `/select` handler but GET made more sense as the request just retrieves data. However, as you mentioned, we reverted to POST in "dev-2.0" due to the 400 error which is thrown by containers in case of extremely long requests.

**Comment by iperminov** [comment]
Agree, from the formal point of view GET has more sense to retrieve data. But from the practical point of view it would be more convenient to use POST to allow long requests. Can I prepare a patch to change GET to POST in the develop branch?

**Comment by aadel** [comment]
Yes, a patch for this makes sense.
