### ISSUE TITLE
Question on panel controller dependency injection

### ISSUE THREAD

**Issue by nickvasilyev** [lucidworks/banana#167]
Hello, 

I have to customize a panel and I need to inject the angular strap $popover service. It works fine through the HTML, but I need to be able to interact with it using JS. 

I inject it like so:
module.controller('fullTextSearch', function($rootScope, $scope, fields, querySrv, dashboard, filterSrv, $location, $popover) {

However, on load I get the following:
Error: Unknown provider: $popoverProvider <- $popover

This happens for other services I try to inject. I've been battling this thing all afternoon and can't figure out why. 

Any idea what is going on here? Now keep in mind, I am relatively new to JS/Angular, so it could be something very simple. Also, I am still on Banana 1.3.

**Comment by suhyunjeon** [comment]
Did you define angularjs strap module in controller.js?
