### ISSUE TITLE
facing an Issur  Oops! undefined field: "event_timestamp"

### ISSUE THREAD

**Issue by Avneets** [lucidworks/banana#19]
Hi i am new to Solr Banana can you please tell me what this error is :-: 
 Oops! undefined field: "event_timestamp".

**Comment by manalisha** [comment]
Hi,
You have to edit the panel and change the time field according to your dataset.

**Comment by Avneets** [comment]
Thanks for the help manalisha,but is it mandatory to give a time field for any new dashboard i create?

**Comment by athana** [comment]
Hi Avneets - It is mandatory to give the time field in a dashboard if you have a time picker panel and/or other panels that depend on time-series data such as a histogram panel.

**Comment by manalisha** [comment]
Hi Avneets,

Suppose you are using the histogram panel,that panel is based in time series data,when you see the solar query inside the module.js file of the histogram panel,they are reading the time field.so if you want any record that does not have any time field you have to write your custom code to rewrite the solr query(not include time field in fq parameter) to reflect that.That will help..
