### ISSUE TITLE
Update installation guide for solr-5.1.0+

### ISSUE THREAD

**Issue by mariusneo** [lucidworks/banana#198]
I've tried to perform an installation of banana to see how it works with solr (version 5.1.0) and had several issues.

> Copy banana folder to $SOLR_HOME/example/solr-webapp/webapp/
> 
> Browse to http://<solr_server>:<port_number>/solr/banana/src/index.html#/dashboard

The correct location within solr-5.1.0 where the banana _directory_ has to be placed is actually
$SOLR_HOME/server/solr-webapp/webapp/

It is worth mentioning that in this case the banana/WEB-INF directory is not actually necessary anymore.

I've tried to install banana on an external server and even though I followed the guideline from https://github.com/LucidWorks/banana/tree/release/resources/enable-cors page (I've downloaded from maven repo the jetty-servlets-8.1.10.v20130312.jar library and placed it into $SOLR_HOME/server/lib and then modified $SOLR_HOME/server/solr-webapp/webapp/WEB-INF/web.xml to include the CrossOriginFilter, I've stumbled into several issues when trying banana web application against my local installation of Solr 5.1.0. Before mentioning them, I'm exposing the configuration of banana web server : 
- Jetty Server 9.2.10
- Solr Server : http://localhost:8983/solr/
- Collection : tweets (i've created it for testing purposes)

After configuring Solr, I get the message exception : 

> Error Could not contact Solr at http://localhost:8983/solr/. Please ensure that Solr is reachable from your system.

even though in the Dev Console I see that the methods all have return code 200.
All the communication with Solr has queries containing no response data (in both FF and Chrome). If i try to perform the solr request with _curl_ it delivers data as expected.

When using the Solr Server : http://localhost:8983/solr/#/ then there are no more exception warnings displayed, but there is a warning saying 

> No collections There were no collections returned from Solr.

It would be very helpful to have an updated guideline on how to perform the installation against Solr 5.1.0+ server.

**Comment by aadel** [comment]
Thanks for pointing this out. In the meantime, there's another _"easier?"_ approach to run Banana on Solr 5.0+ which is to run `ant` then copy the build WAR file to `server/webapps` and create a new context for Banana under `server/contexts` directory. The URL should be something like _http://localhost:8983/banana_.

In case of running against remote Solr instance, CORS correspondning directories should be `server/solr-webapp/webapp/WEB-INF/lib/` and `server/solr-webapp/webapp/WEB-INF/web.xml`. All paths are relative to `$SOLR_HOME`.

**Comment by mariusneo** [comment]
@aadel thank you for the tip.
I've created a separate context for banana within $solr_home/server/context/banana-jetty-context.xml file with the content 

```
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath"><SystemProperty name="hostContext" default="/banana"/></Set>
  <Set name="war"><SystemProperty name="jetty.home"/>/webapps/banana.war</Set>
  <Set name="defaultsDescriptor"><SystemProperty name="jetty.home"/>/etc/webdefault.xml</Set>
  <Set name="tempDirectory"><Property name="jetty.home" default="."/>/banana-webapp</Set>
</Configure>
```

Indeed I can now run the banana application on the same jetty server used for the Solr instance under the link : http://localhost:8983/banana/#/dashboard

> In case of running against remote Solr instance, CORS correspondning directories should be server/solr-webapp/webapp/WEB-INF/lib/

I moved the jetty libraries (jetty-servlets and jetty-util) to `server/solr-webapp/webapp/WEB-INF/lib` but I still face the same issues as before when running against the remote Solr instance (the ajax HTTP responses have status code 200, but they are empty). Any ideas for this usecase?

**Comment by aadel** [comment]
> I moved the jetty libraries (jetty-servlets and jetty-util) to server/solr-webapp/webapp/WEB-INF/lib but I still face the same issues as before when running against the remote Solr instance (the ajax HTTP responses have status code 200, but they are empty). Any ideas for this usecase?

@mariusneo please check the updated [guide](https://github.com/LucidWorks/banana/tree/develop/resources/enable-cors), paths and Jetty JAR's are slightly different under Solr 5.

**Comment by mariusneo** [comment]
@aadel  thank you for the tip regarding the position of the cors filter (right after the web-app element). This was the thing that I missed.
