### ISSUE TITLE
Panels from kibana

### ISSUE THREAD

**Issue by knewter** [lucidworks/banana#2]
There are several panels from kibana that are missing (map, bettermap, some features in the histogram, etc).  Is it trivial to add them into banana?  I'm very familiar with both angularjs and solr, so hoping it's not a big deal, but before I dug in I thought I'd ask here.

**Comment by ravikmurthy** [comment]
Josh,

After a few iterations, we have  worked out what we need to do while  modifying a kibana panel to work with Solr. We have not yet tried creating a brand new module.

If you know angular and solr, it should not be very difficult to do the US map. I have not looked hard at the bettermap as yet.

We have added some of the missing features in the histogram (see latest check in on develop branch). For the others (max,min,mean) we are still looking at the best approach. 

Regards
Ravi

Sent via BlackBerry from T-Mobile

-----Original Message-----

**Comment by knewter** [comment]
I don't have a use case for the US map at present, and so am ignoring it.  I'll close this issue, but I'm opening another with some potential style updates

**Comment by athana** [comment]
Josh, I plan on writing a HOWTO article on developing a custom module to Banana. Hope that it'll be helpful for you in case you want to write your own panels.
