### ISSUE TITLE
Panel Map: Height problem under IE 9-11

### ISSUE THREAD

**Issue by jbrucher** [lucidworks/banana#200]
Hi,
found a bug within Banana for the panel "map". In IE 9 - 11 the panel height or row height is not recognized probably and therefor a default height of 20px is always set.
So the statement:
`<div class="jvectormap" map params="{{panel}}" style="height:{{panel.height || row.height}}"></div>`
(https://github.com/LucidWorks/banana/blob/release/src/app/panels/map/module.html#L62)
should be changed to:
`<div class="jvectormap" map params="{{panel}}" ng-style="{height:panel.height || row.height}"></div>`
than its working fine in both FF and IE.

**Comment by aadel** [comment]
Hi @jbrucher a PR to `develop` branch is welcome!

**Comment by jbrucher** [comment]
Hi @aadel the PR can be found here: https://github.com/LucidWorks/banana/pull/204

**Comment by aadel** [comment]
Merged
