### ISSUE TITLE
Publish Banana WAR to Maven Central

### ISSUE THREAD

**Issue by lewismc** [lucidworks/banana#201]
Hi Folks,
We are interested in being able to pull down a Banana WAR file with Maven and have it packaged and ready to go as part of a distribution. 
I have been working on the Maven Ant tasks which would produce the WAR artifact, sign it and publish it to OSSRH which would then enable us to sync it over to Maven Central.
I would just like for you guys to verify a couple of things for me before I begin pushing with SonaType OSSRH. 
What would you guys like to define within the following?
groupId
artifactId

Thanks
Lewis

**Comment by lewismc** [comment]
Hi Folks, I've gone ahead and created a ticket for a repository to be created for Banana on OSSRH.
https://issues.sonatype.org/browse/OSSRH-15831
I'll report back here with all updates.

**Comment by aadel** [comment]
+1

**Comment by lewismc** [comment]
Hi Folks, we are ready to push a .war artifact to Maven Central. 
Joel Orlina has set us up and configuration has been prepared, so we can:
- Deploy snapshot artifacts into repository https://oss.sonatype.org/content/repositories/snapshots
- Deploy release artifacts into the staging repository https://oss.sonatype.org/service/local/staging/deploy/maven2
- Promote staged artifacts into repository 'Releases'
- Download snapshot and release artifacts from group https://oss.sonatype.org/content/groups/public
- Download snapshot, release and staged artifacts from staging group https://oss.sonatype.org/content/groups/staging

**Comment by lewismc** [comment]
Banana Project 1.5.1 artifacts have been released and will be available in Maven Central once the sync from OSSRH is complete folks. I'll update here once they have been sync'd.

**Comment by athana** [comment]
Thanks @lewismc  I merged your PR https://github.com/LucidWorks/banana/pull/203 into `develop` branch.

**Comment by lewismc** [comment]
Thank you @athana

**Comment by covolution** [comment]
Banana 1.6.0 doesn't seem to be in maven central

**Comment by lewismc** [comment]
@covolution I would assume that the deploy target has not been added to the release process!
