### ISSUE TITLE
Sort collection names in the Collection Picker

### ISSUE THREAD

**Issue by athana** [lucidworks/banana#218]
![screen shot 2015-06-17 at 1 45 04 pm](https://cloud.githubusercontent.com/assets/974546/8218323/20670bfc-14f7-11e5-987b-b15650bd9568.png)

**Comment by davidfmiller** [comment]
I believe this is fixed in the `develop` branch?

**Comment by athana** [comment]
@davidfmiller  Oh yes it does (I forgot to update) Thanks!
