### ISSUE TITLE
Can we use banana.war at Enterprise level for free 

### ISSUE THREAD

**Issue by ckreddybh** [lucidworks/banana#254]
As  licence at github says
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

So it means we can use the banana.war at our business level or we should buy any commercial licence

**Comment by athana** [comment]
@ckreddybh  Yes, Apache license allows us to use it for free.
