### ISSUE TITLE
1.6.0 release names war file 1.5.1.

### ISSUE THREAD

**Issue by eldryoth** [lucidworks/banana#266]
Hello,

I noticed that when you build a war file for the 1.6.0 release it names it actually 1.5.1 see below.

This are the steps I perform:
wget https://github.com/LucidWorks/banana/archive/v1.6.0.tar.gz
tar xvzf v1.6.0.tar.gz
mkdir -p /home/ulyaoth/banana-1.6.0/build
 cd /home/ulyaoth/banana-1.6.0
ant

result is:
Buildfile: /home/ulyaoth/banana-1.6.0/build.xml

build-war:
      [war] Building war: /home/ulyaoth/banana-1.6.0/build/banana-1.5.1.war

BUILD SUCCESSFUL

**Comment by athana** [comment]
Fixed. Thanks @sbagmeijer
