### ISSUE TITLE
one Dashboard and multiple Solr core

### ISSUE THREAD

**Issue by zhangzy0317** [lucidworks/banana#275]
**[Prerequisite description]**
  1 . one  Dashboard
  2 . one  Solr  server
      ※multiple core ：collection1,※ (index:id=001)
      　　　　　　　　collection2,※ (index:id=002)
      　　　　　　　　collection3,※ (index:id=003)
      　　　　　　　　collection4 ※ (index:id=004)
**[expect result]**
    example：The index data (id:001~004) is displayed in the same  pie chart at the hits panel
**[question]**
    Is there  a way one dashboard can read data from multiple  core ?
    How to set it?
  // Sorry, my English level is low.
Thank you very much!

**Comment by yeeplusplus** [comment]
Have you tried listing them in the `solr.server.core_list` object in the dashboard's JSON?

**Comment by zhangzy0317** [comment]
Thanks for your answer.
But I can not understand . 
So I modified the question .
Please check it again.

**Comment by yeeplusplus** [comment]
Post your dashboard file

**Comment by zhangzy0317** [comment]
Sorry. Upload file is prohibited in the company's network. Upload error.
My dashboard is just a very ordinary file.
Thanks  very much for your answer.

**Comment by zhangzy0317** [comment]
Yeeplusplus . Thanks for your help.
My question is solved.
solved method:use [slorcloud ]or [Multiple Cores]. Don't modify banana tool.
Thanks for your answer.
