### ISSUE TITLE
Error while loading the index,html file

### ISSUE THREAD

**Issue by souravprakashjena** [lucidworks/banana#294]
when i am loading the index.html file at that time page is loaded but no charts are shown .Irs showing a error that : **Error Could not contact Solr at localhost:8983/solr/. Please ensure that Solr is reachable from your system.**

I am using solar 6.1.0 version

Please find the screenshot below

![image](https://cloud.githubusercontent.com/assets/13752535/21008953/22b347c8-bd6a-11e6-9c14-25a63b7e4255.png)

**Comment by aadel** [comment]
Are you sure that Solr is up and `http://localhost:8983/` is accessible?

**Comment by souravprakashjena** [comment]
Yes it is up....can u please help me out???

**Comment by souravprakashjena** [comment]
In browser console its showing the following error.

![image](https://cloud.githubusercontent.com/assets/13752535/21038018/565130fc-bdf8-11e6-838c-a58625c9e966.png)

**Comment by aadel** [comment]
Which version/branch are you using? Form the last screenshot, the URL `%3172.25.1....` seems weird. Looks like a typo somewhere.

**Comment by souravprakashjena** [comment]
Banana v1.6.0

**Comment by aadel** [comment]
Looks like the "Server" value in Dashboard Settings is misconfigured. Try removing the `IP:port` portion and just leave the path `\solr\`.

**Comment by souravprakashjena** [comment]
ya that got fixed ....thanks a lot.....Do you have any extra documentation regarding execution flow of banana??

**Comment by aadel** [comment]
Welcome! The default dashboard text panels (at the top) give a good overview for starting points and how to proceed.

You may also check the official [docs](https://doc.lucidworks.com/lucidworks-hdpsearch/2.5/Guide-Banana.html) for panels reference.

This [wiki page](https://github.com/lucidworks/banana/wiki/Tutorial:-How-to-Build-a-Custom-Panel) explains how to create custom panels.
