### ISSUE TITLE
Cannot store a dashboad when using a remote server

### ISSUE THREAD

**Issue by jetnet** [lucidworks/banana#295]
hi guys!

I'd like to have a dedicated small solr instance for Banana (v1.6.11) only (localhost:8111) and a working Solr instance with data (localhost:8008):

config.js
```javascript
    // Specify Solr server and core to store the data.
    // solr: "/api/apollo/solr/",
    solr: "http://localhost:8111/solr/",
    solr_core: "logs",
    timefield: "@timestamp",

    banana_index: "banana",
```

and the config of a dashboard:
Solr Server / Fusion Query Pipeline: ```http://localhost:8008/solr/```
Collection Name: ```project```

The UI (http://localhost:8111/solr/banana/index.html) can connect and visualize data from the "remote" instance (port:8008), but when I try to save the dashboad, it uses the *remote* instance (port:8008 not the "local" one - 8111) to store the dashboard:
http://localhost:8008/solr/banana/update?commit=true
Obviously, the request returns 404 - "not found", because the "banana" index exist in the "local" instance only.
Question: why Banana does use the "Solr Server" URL from the dashboard's settings and not the "main" one from the "config.js" to store its own data?

Thank you!

**Comment by mosuka** [comment]
Hi @jetnet ,

That problem is probably resolved in 1.6.12. Please see following PR:

https://github.com/lucidworks/banana/pull/279

**Comment by jetnet** [comment]
hi @mosuka,

First of all thank you for the fast reply!
it's very interesting! It turned out, I'm already using the latest DEV release of Banana.

So, it is not a bug, it is a feature? Why dashboards should be stored in a "remote" instance?
From my point of view, it worked correctly before #279 - the dashboards were stored in the *local* Banana instance. I thought, this is the way how it should work.
And now we have to create a "banana-int" core in every Solr server, that we are trying to connect to?

Thanks!

**Comment by mosuka** [comment]
Banana (localhost:8111) visualizes the data of connected Solr (localhost:8008). Also, it stores dashboard settings to the same Solr (localhost:8008).

**Comment by jetnet** [comment]
So, could you guys please confirm, that storing Banana dashboards in a *dedicated* solr instance is __not__ supported by design?
Thank you!

UPDATE:
I have an environment with a lot of stand-alone single core Solr instances (one instance - one core [or collection]) and adding another "banana" core for every Solr instance is not an option.
So, it'd great, if Banana could be configured where the internal data (dashboards) could be stored - in the "internal" (dedicated) Solr instance or along with analyzed data.
Thanks!

**Comment by aadel** [comment]
hi @jetnet the current version of Banana does not support storing/loading dashboards from local server as per https://github.com/lucidworks/banana/pull/279, but check PR https://github.com/lucidworks/banana/pull/297 that would give an option to store/load dashboards from either local or remote servers based on settings.

**Comment by jetnet** [comment]
fantastic! thanks a lot!

**Comment by athana** [comment]
@jetnet @aadel @mosuka  I added the feature to save / load dashboards from another Solr server in the latest commit to `develop` branch. It will be included in the next release. Notes that we will need to enable CORS in the remote Solr server in order to allow dashboard to be saved and loaded. Instructions are here:
https://github.com/lucidworks/banana/tree/develop/resources/enable-cors
