### ISSUE TITLE
Banana with Zookeeper & SolrCloud 

### ISSUE THREAD

**Issue by rohanganpatye** [lucidworks/banana#30]
I have a standalone ZooKeeper instance running locally on port 2181 with 3 Solr Servers running locally on 3 different ports.  I wish to create dashboards for a single collection split across these 3 solr instances using Banana. 

Can someone please help me understand how do I set up Banana to do this effectively for me?

Thanks!
PS: I followed the setup instructions from the github page for a single Solr server on 8983 and it runs fine.

**Comment by adamjlucid** [comment]
To get Banana working with this, from the dashboard click on the cog in the upper right hand of the page.  This will bring you to the dashboard configuration view, and from the Solr tab put the end point of any of the collections into the server dialogue box.  Solr Cloud will automatically distribute the queries it receives throughout the available nodes.

Make sure to format the url you use as if it were being called from a browser/external source, i.e.
http://SERVER_NAME:8983/solr/  and provide the name of the collection you are referencing.

**Comment by rohanganpatye** [comment]
Thanks for the help!

**Comment by DipakRai** [comment]
@rohanganpatye @adamjlucid  Does this really work? Can you access the banana dashboard with Solr running in cloud mode as mentioned above? "put the end point of any of the collections into the server dialogue box" : what if the URL you provided in the cog of the dashboard against Solr Collections is DOWN? The Zookeeper would manage the traffic for the Solr Client internally through its configuration file. But for the banana dashboard who does this managing? The Zookeeper is not even aware of the presence of a banana dashboard and cannot reroute the dashboard query to a different Solr instance running in the cloud.

**Comment by DipakRai** [comment]
https://stackoverflow.com/questions/55376984/how-to-access-banana-dashboard-for-solr-while-running-solr-in-cloud-mode
Please check this Qs.
