### ISSUE TITLE
Other value slice and legends appears always zero while appearing other checkbox enabled(mode:count)

### ISSUE THREAD

**Issue by banajit** [lucidworks/banana#36]
Use Case: Top k results (count) from the result set(1,2…..k……..n)
What banana UI has done here is, since solr faceting doesn’t return they have just hardcoded value to 0.
Solutions: 
Other Value count = Total Number of hits – (Sum of Top k results)
Where Total Number of hits can be found from the sole numFound

**Comment by aadel** [comment]
Thanks for the report. The fix will take place in the next release of Banana.

**Comment by tarek-salah** [comment]
I fixed this issue and will be in the next release. Thanks

**Comment by aadel** [comment]
@banajit: check 3e2b1fd326195b96a6585158e43798fbf170227d for the fix of this issue.
