### ISSUE TITLE
No able to load the dashboard due to angular.js:5930 EvalError

### ISSUE THREAD

**Issue by vidyuthmk** [lucidworks/banana#370]
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'". 
at 5930 line code "return logFn.apply(console, args);"

**Comment by vidyuthmk** [comment]
I got this issue , it is due to CSP violation .

**Comment by norbwww** [comment]
Has anyone been to get to the bottom of this?
Thanks

**Comment by vidyuthmk** [comment]
The issue was due to a violation of CSP content security policies of the web Browsers. you need to BYPASS CSP of the browser to avoid these issues
