### ISSUE TITLE
term value being split by the dash character

### ISSUE THREAD

**Issue by meetri** [lucidworks/banana#41]
When creating a terms panel using a field that contains a dash there are issues with the value being split by the dash character. Is there a solution for this?

**Comment by aadel** [comment]
Perhaps you should use [KeywordTokenizer](https://cwiki.apache.org/confluence/display/solr/Tokenizers#Tokenizers-KeywordTokenizer) for that specific field in your Solr schema configuration. Standard and Calssic tokenizers by default split field values by hyphens.

**Comment by aadel** [comment]
Or you could use field of type `string` which does not perform tokenization.
