### ISSUE TITLE
Custom Queries are not working with Histograms

### ISSUE THREAD

**Issue by ahakkou** [lucidworks/banana#50]
I only tested with histograms and it does not seem to work. Maybe it is the same for terms.

**Comment by aadel** [comment]
Just checked with version 1.4 and custom queries are working fine with histogram. Please post the query you have in the inspect dialog to take a deeper look.

**Comment by ahakkou** [comment]
![image](https://cloud.githubusercontent.com/assets/8970097/4458292/9e0b00f4-48a1-11e4-99ec-7be4a336198b.png)

**Comment by aadel** [comment]
Custom query should be entered in the following format:

&fq=text:2G

**Comment by ahakkou** [comment]
Ok it works if i do this:

![image](https://cloud.githubusercontent.com/assets/8970097/4458346/2122d818-48a2-11e4-9380-5c4f10a868ee.png)

Sorry for bothering you
