### ISSUE TITLE
Reset Range Facet Min/Max Values

### ISSUE THREAD

**Issue by nickvasilyev** [lucidworks/banana#52]
When I select a range using the range facet panel it gets added to the criteria and the dashboard is reloaded. However, when I delete it from the filter criteria, the range facet panel complains about lack of range filter. If I click to create a new one, it puts in the same one as I had in there last time. To get the original range back, I have to go into the panel settings and re-configure it. This would not be possible if the dashboard is opened to the end users and settings cog is taken out. 

There should be a reset button in the panel somewhere that would get back the pre-configured range in the settings.

**Comment by aadel** [comment]
Thanks for reporting, we will be working on a fix for this.
