### ISSUE TITLE
Table panel - offset not cleared after 'refresh' event

### ISSUE THREAD

**Issue by bieniek** [lucidworks/banana#99]
Currently there is a problem with paging on table panel. Offset (page no.) will not be revert to 0 after broadcasting 'refresh' event so in case one move to further page and then choose from Timestamp panel other period - table will still display page with previous offset. 

Something like:
src/app/panels/table/module.js
l.105; $scope.$on('refresh',function(){**$scope.panel.offset=0;**$scope.get_data();});

will fix the problem.

**Comment by bieniek** [comment]
Problem should be resolved after pulling 

https://github.com/LucidWorks/banana/pull/100

Regards,
Michal

**Comment by aadel** [comment]
Thanks for reporting this issue! Closed via https://github.com/LucidWorks/banana/pull/100
